DROP TABLE IF EXISTS seamless;

CREATE TABLE seamless (
    sl_link text,
    vend_id bigint,
    vend_name text,
    description text,
    cuisine text,
    catering text,
    address text,
    zipcode integer,
    phone bigint,
    price double precision,
    rating double precision,
    rating_total integer,
    rating_perc double precision,
    reviews double precision,
    pickup_est text,
    deliv_est text,
    deliv_min double precision,
    deliv_fee double precision,
    perc_fee bigint,
    search_link_blob text,
    estimates_blob text,
    upd_search_links timestamp with time zone,
    upd_vend_content timestamp with time zone,
    inactive boolean DEFAULT false,
    camis bigint,
    bbl integer,
    lot_cnt integer DEFAULT 1,
    geom geometry(Point,4326),
    id integer NOT NULL DEFAULT nextval('seamless_id_seq'::regclass),
    norm_addr text,
    vent_cnt_per_lot integer,
    qgis_selection boolean,
    recent_deliv_cmts boolean DEFAULT false,
    skipped boolean DEFAULT false,
    y_vend_id text,
    checked_out text,
    scrape_address text,
    last_updated timestamp with time zone,
    bldg text,
    box text,
    unit text,
    num text,
    predir text,
    street_name text,
    suftype text,
    sufdir text,
    bldg_street_idx text,
    sm integer DEFAULT 0,
    ls integer DEFAULT 0,
    gc_lat double precision,
    gc_lon double precision,
    gc_full_addr text,
    ai integer DEFAULT 0,
    pa text,
    tmp boolean DEFAULT false,
    tmp_i integer,
    trigger_step text,
    gc_addr text,
    gc_zip bigint,
    orig_addr text,
    CONSTRAINT seamless_pkey PRIMARY KEY (id)
)